services:
  localstack:
    container_name: localstack-main
    image: localstack/localstack-pro
    ports:
      - "0.0.0.0:4566:4566"             # LocalStack Gateway    
      - "0.0.0.0:4510-4559:4510-4559"   # external service port range
      - "0.0.0.0:443:443"               # LocalStack HTTPS Gateway
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}
    volumes:
      - "./volumes/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      lsworkbench:
        ipv4_address: 10.0.2.20
    restart: unless-stopped

  webtop:
    build:
      context: .
      dockerfile: DockerfileWebtop
    container_name: webtop
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - CUSTOM_USER=lswb
      - TZ=Etc/UTC
      - SUBFOLDER=/
      - TITLE=LocalStack Workbench
    volumes:
      - ./volumes/webtop:/config
      - ./configs/webtop/aws:/config/.aws
      - ./configs/webtop/bashrc:/config/.bashrc
      - ./configs/webtop/Desktop/Jenkins.desktop:/config/Desktop/Jenkins.desktop
      - ./configs/webtop/Desktop/KeyCloak.desktop:/config/Desktop/KeyCloak.desktop
      - ./configs/webtop/Desktop/OpenLDAP-UI.desktop:/config/Desktop/OpenLDAP-UI.desktop
      - ./configs/webtop/Desktop/Docmost.desktop:/config/Desktop/Docmost.desktop
      - ./configs/webtop/Desktop/PGAdmin4.desktop:/config/Desktop/PGAdmin4.desktop
      - ./configs/webtop/Desktop/Pycharm.desktop:/config/Desktop/Pycharm.desktop
      - ./configs/webtop/Desktop/open-lens.desktop:/config/Desktop/open-lens.desktop
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      - lsworkbench
    dns: 10.0.2.20
    ports:
      - 3000:3000
      - 3001:3001
# can be enabled on linux hosts to speed up things a bit:
#    devices:
#      - /dev/dri:/dev/dri #optional
    shm_size: "1gb"
    restart: unless-stopped

networks:
  lsworkbench:
    name: lsworkbench
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
          
