services:
  postgresql:
    container_name: postgres
    restart: unless-stopped
    image: docker.io/bitnami/postgresql:latest
    environment:
      # don't do in real life!
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=keycloak_db
      # comma separated list, eg. db2,db3:
      - POSTGRESQL_ADDITIONAL_DATABASES=docmost
    volumes:
      - "./volumes/postgresql_data:/bitnami/postgresql"
      - "./configs/postgres/init.sh:/docker-entrypoint-initdb.d/initdb.sh"
#    ports:
#      - '5432:5432'
    networks:
      - lsworkbench
    dns: 10.0.2.20
  pgadmin4:
    container_name: pgadmin
    restart: unless-stopped
    depends_on:
      - postgresql
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@lswb.lan
      - PGADMIN_DEFAULT_PASSWORD=im-local-admin
      - PGADMIN_DISABLE_POSTFIX=true
      - PGADMIN_SERVER_JSON_FILE=/config/servers.json
      - PGADMIN_PREFERENCES_JSON_FILE=/config/preferences.json
    volumes:
      - "./volumes/pgadmin/config:/config"
      - "./volumes/pgadmin/lib:/var/lib/pgadmin"
    networks:
      - lsworkbench
    dns: 10.0.2.20
  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:7.2-alpine
    volumes:
      - "./volumes/redis/data:/data"
    networks:
      - lsworkbench
    dns: 10.0.2.20
  openldap:
    container_name: openldap
    restart: unless-stopped
    image: osixia/openldap:1.5.0
    ports:
      - '389:389'
      - '636:636'
    environment:
      - LDAP_ORGANISATION=lswb
      - LDAP_DOMAIN=lswb.lan
      - LDAP_ADMIN_PASSWORD=im-local-admin
      - LDAP_CONFIG_PASSWORD=config
      - LDAP_RFC2307BIS_SCHEMA=true
      - LDAP_TLS=true
      - LDAP_TLS_ENFORCE=false
      - LDAP_TLS_CA_CRT_FILENAME=ca.crt
      - LDAP_TLS_CRT_FILENAME=openldap.crt
      - LDAP_TLS_KEY_FILENAME=openldap.key
      - LDAP_TLS_VERIFY_CLIENT=try
    networks:
      - lsworkbench
    dns: 10.0.2.20
    volumes:
      - './volumes/openldap/data:/var/lib/ldap'
      - './volumes/openldap/slapd.d:/etc/ldap/slapd.d'
      - './configs/openldap/certs:/container/service/slapd/assets/certs'
  openldap-ui:
    image: wheelybird/ldap-user-manager:latest
    container_name: openldap-ui
    depends_on:
      - openldap
    restart: unless-stopped
    environment:
      - LDAP_URI=ldaps://openldap:636
      - LDAP_BASE_DN=dc=lswb,dc=lan
      - LDAP_REQUIRE_STARTTLS=TRUE
      - LDAP_ADMINS_GROUP=admins
      - LDAP_ADMIN_BIND_DN=cn=admin,dc=lswb,dc=lan
      - LDAP_ADMIN_BIND_PWD=im-local-admin
      - LDAP_IGNORE_CERT_ERRORS=true
      - LDAP_TLS_CACERT_FILE=/opt/certs/ca.crt
      - LDAP_USER_OU=users
      - LDAP_DEBUG=TRUE
      #- LDAP_VERBOSE_CONNECTION_LOGS=TRUE
      - FORCE_RFC2307BIS=TRUE
      #- SHOW_POSIX_ATTRIBUTES=FALSE
      - NO_HTTPS=TRUE
      - PASSWORD_HASH=SSHA
      - SERVER_HOSTNAME=openldap-ui
      - SERVER_PORT=18080
    volumes:
      - './configs/openldap/certs:/opt/certs'
    ports:
      - 18080:18080
    networks:
      - lsworkbench
    dns: 10.0.2.20
  keycloak:
    container_name: keycloak
    restart: unless-stopped
    depends_on:
      - postgresql
    image: docker.io/bitnami/keycloak:latest
    networks:
      - lsworkbench
    dns: 10.0.2.20
#    ports:
#	port not exposed to outside lsworkbench network
#      - "8080:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=im-local-admin
      - KEYCLOAK_DATABASE_USER=postgres
      - KEYCLOAK_DATABASE_NAME=keycloak_db
  docmost:
    container_name: docmost
    depends_on:
      - postgresql
      - redis
    image: docmost/docmost:latest
    ports:
      - '3080:3000'
    environment:
      APP_URL: "http://docmost"
      APP_SECRET: "MYOWNCUSTOMLSWORKBENCHSECRET"
      DATABASE_URL: "postgresql://postgres:postgres@postgresql:5432/docmost?schema=public"
      REDIS_URL: "redis://redis:6379"
    networks:
      - lsworkbench
    dns: 10.0.2.20
    volumes:
      - './volumes/docmost/data:/app/data/storage'

networks:
  lsworkbench:
    # is defined in main docker-compose.yaml
    external: true
    name: lsworkbench
