services:
  jenkins:
    container_name: jenkins
    restart: unless-stopped
    build:
      context: .
      dockerfile: DockerfileJenkins
    privileged: true
    user: root
    networks:
      - lsworkbench
    dns: 10.0.2.20
#    ports:
#      - 8880:8080
#      - 50000:50000
    volumes:
      - ./volumes/jenkins:/var/jenkins_home
      - ./configs/jenkins/terraform:/opt/terraform/terraform
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  lsworkbench:
    # is defined in main docker-compose.yaml
    external: true
    name: lsworkbench
